// Central registry for all menu items - add new items here and they'll auto-sync to database
import {
  LayoutDashboard,
  Users,
  Calendar,
  FileText,
  BarChart3,
  Settings,
  UserPlus,
  MessageSquare,
  Bell,
  Clock,
  CheckSquare,
  Tag,
  Link2,
  Layout,
  Eye,
  Mail,
  Phone,
  Slack,
  Layers,
  GraduationCap,
  ClipboardList,
  FolderOpen,
  UserCog,
  HelpCircle,
  TrendingUp,
  DollarSign,
  type LucideIcon,
} from "lucide-react"

export interface MenuItemDefinition {
  key: string
  label: string
  description: string
  category: "navigation" | "management" | "communication" | "administration" | "analytics"
  type: "sidebar" | "dashboard"
  icon?: string
  href?: string
  defaultRoles?: string[] // Roles that should have access by default
}

// Define all menu items here - they will auto-sync to the database
export const MENU_REGISTRY: MenuItemDefinition[] = [
  // Sidebar Navigation Items
  {
    key: "dashboard",
    label: "Dashboard",
    description: "Main dashboard overview",
    category: "navigation",
    type: "sidebar",
    icon: "LayoutDashboard",
    href: "/dashboard",
    defaultRoles: ["lead_admin", "admin", "member", "volunteer"],
  },
  {
    key: "giving",
    label: "Giving",
    description: "Donation management and analytics",
    category: "management",
    type: "sidebar",
    icon: "DollarSign",
    href: "/dashboard/giving",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "unity",
    label: "Unity",
    description: "Custom kanban boards section",
    category: "navigation",
    type: "sidebar",
    icon: "Layers",
    href: "/dashboard/unity",
    defaultRoles: ["lead_admin", "admin", "member", "volunteer"],
  },
  {
    key: "unity-roadmap",
    label: "Table View Roadmap",
    description: "Roadmap for Monday.com-style table view",
    category: "navigation",
    type: "sidebar",
    icon: "FileText",
    href: "/dashboard/unity/roadmap",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "visitors",
    label: "Visitors",
    description: "Visitor management kanban board",
    category: "navigation",
    type: "sidebar",
    icon: "Users",
    href: "/dashboard/visitors",
    defaultRoles: ["lead_admin", "admin", "member"],
  },
  {
    key: "calendar",
    label: "Calendar",
    description: "Church events calendar",
    category: "navigation",
    type: "sidebar",
    icon: "Calendar",
    href: "/dashboard/calendar",
    defaultRoles: ["lead_admin", "admin", "member", "volunteer"],
  },
  {
    key: "rundown",
    label: "Rundown",
    description: "Service rundown management",
    category: "navigation",
    type: "sidebar",
    icon: "FileText",
    href: "/dashboard/rundown",
    defaultRoles: ["lead_admin", "admin", "member", "volunteer"],
  },
  {
    key: "analytics",
    label: "Analytics",
    description: "Visitor and team analytics",
    category: "navigation",
    type: "sidebar",
    icon: "BarChart3",
    href: "/dashboard/analytics",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "team",
    label: "Team",
    description: "Team member management",
    category: "management",
    type: "sidebar",
    icon: "Users",
    href: "/dashboard/team",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "classes",
    label: "Classes",
    description: "Class management system",
    category: "management",
    type: "sidebar",
    icon: "Users",
    href: "/dashboard/classes",
    defaultRoles: ["lead_admin", "admin", "member"],
  },
  {
    key: "attendance",
    label: "Attendance",
    description: "Attendance tracking",
    category: "management",
    type: "sidebar",
    icon: "CheckSquare",
    href: "/dashboard/attendance",
    defaultRoles: ["lead_admin", "admin", "member"],
  },
  {
    key: "slack-integration",
    label: "Slack Integration",
    description: "Slack workspace integration",
    category: "communication",
    type: "sidebar",
    icon: "Slack",
    href: "/dashboard/slack",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "scheduled-alerts",
    label: "Scheduled Alerts",
    description: "Automated Slack notifications",
    category: "communication",
    type: "sidebar",
    icon: "Bell",
    href: "/dashboard/alerts",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "settings",
    label: "Settings",
    description: "Church tenant settings",
    category: "administration",
    type: "sidebar",
    icon: "Settings",
    href: "/dashboard/settings",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "menu-visibility",
    label: "Menu Visibility",
    description: "Configure role-based menu visibility",
    category: "administration",
    type: "sidebar",
    icon: "Eye",
    href: "/dashboard/settings/menu-visibility",
    defaultRoles: ["lead_admin"],
  },
  {
    key: "support",
    label: "Help & Support",
    description: "Get help or request features",
    category: "navigation",
    type: "sidebar",
    icon: "HelpCircle",
    href: "/dashboard/support",
    defaultRoles: ["lead_admin", "admin", "member", "volunteer"],
  },
  {
    key: "email-settings",
    label: "Email Settings",
    description: "Customize email branding and templates",
    category: "administration",
    type: "sidebar",
    icon: "Mail",
    href: "/dashboard/settings/email",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "email-analytics",
    label: "Email Analytics",
    description: "Track email performance and engagement",
    category: "analytics",
    type: "sidebar",
    icon: "TrendingUp",
    href: "/dashboard/analytics/email",
    defaultRoles: ["lead_admin", "admin"],
  },

  // Dashboard Cards
  {
    key: "dashboard_visitors",
    label: "Visitors",
    description: "Manage visitor information",
    category: "management",
    type: "dashboard",
    icon: "Users",
    href: "/dashboard/visitors",
    defaultRoles: ["lead_admin", "admin", "member"],
  },
  {
    key: "dashboard_giving",
    label: "Giving",
    description: "View donation analytics",
    category: "management",
    type: "dashboard",
    icon: "DollarSign",
    href: "/dashboard/giving",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "dashboard_calendar",
    label: "Calendar",
    description: "View and manage events",
    category: "navigation",
    type: "dashboard",
    icon: "Calendar",
    href: "/dashboard/calendar",
    defaultRoles: ["lead_admin", "admin", "member", "volunteer"],
  },
  {
    key: "dashboard_attendance",
    label: "Attendance",
    description: "Track attendance records",
    category: "management",
    type: "dashboard",
    icon: "BarChart3",
    href: "/dashboard/attendance",
    defaultRoles: ["lead_admin", "admin", "member"],
  },
  {
    key: "dashboard_teams",
    label: "Teams",
    description: "Manage ministry teams",
    category: "management",
    type: "dashboard",
    icon: "Layers",
    href: "/dashboard/teams",
    defaultRoles: ["lead_admin", "admin", "member"],
  },
  {
    key: "dashboard_classes",
    label: "Classes",
    description: "Manage church classes",
    category: "management",
    type: "dashboard",
    icon: "GraduationCap",
    href: "/dashboard/classes",
    defaultRoles: ["lead_admin", "admin", "member"],
  },
  {
    key: "dashboard_newsletter",
    label: "Newsletter",
    description: "Send email newsletters",
    category: "communication",
    type: "dashboard",
    icon: "Mail",
    href: "/dashboard/newsletter",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "dashboard_sms",
    label: "SMS Notifications",
    description: "Schedule and send SMS",
    category: "communication",
    type: "dashboard",
    icon: "Bell",
    href: "/dashboard/sms-notifications",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "dashboard_rundowns",
    label: "Rundowns",
    description: "Service rundowns",
    category: "management",
    type: "dashboard",
    icon: "ClipboardList",
    href: "/dashboard/rundowns",
    defaultRoles: ["lead_admin", "admin", "member", "volunteer"],
  },
  {
    key: "dashboard_slack",
    label: "Slack",
    description: "Team communication",
    category: "communication",
    type: "dashboard",
    icon: "MessageSquare",
    href: "/dashboard/slack",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "dashboard_media",
    label: "Media Assets",
    description: "Manage media files",
    category: "management",
    type: "dashboard",
    icon: "FolderOpen",
    href: "/dashboard/media-assets",
    defaultRoles: ["lead_admin", "admin", "member"],
  },
  {
    key: "dashboard_users",
    label: "Users",
    description: "Manage church members",
    category: "administration",
    type: "dashboard",
    icon: "UserCog",
    href: "/dashboard/users",
    defaultRoles: ["lead_admin", "admin"],
  },
  {
    key: "dashboard_settings",
    label: "Settings",
    description: "Church configuration",
    category: "administration",
    type: "dashboard",
    icon: "Settings",
    href: "/dashboard/settings",
    defaultRoles: ["lead_admin", "admin"],
  },
]

// Helper to get icon component by name
export const getIconComponent = (iconName: string): LucideIcon | null => {
  const icons: Record<string, LucideIcon> = {
    LayoutDashboard,
    Users,
    Calendar,
    FileText,
    BarChart3,
    Settings,
    UserPlus,
    MessageSquare,
    Bell,
    Clock,
    CheckSquare,
    Tag,
    Link2,
    Layout,
    Eye,
    Mail,
    Phone,
    Slack,
    Layers,
    GraduationCap,
    ClipboardList,
    FolderOpen,
    UserCog,
    HelpCircle,
    TrendingUp,
    DollarSign,
  }
  return icons[iconName] || null
}
