import { type NextRequest, NextResponse } from "next/server"
import Stripe from "stripe"
import { createClient } from "@/lib/supabase/server"
import { asyncHandler, ValidationError, DatabaseError } from "@/lib/errors/handler"

function getStripeClient() {
  return new Stripe(process.env.STRIPE_SECRET_KEY!, {
    apiVersion: "2024-12-18.acacia",
  })
}

export const POST = asyncHandler(async (request: NextRequest) => {
  const stripe = getStripeClient()
  const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET!
  const body = await request.text()
  const signature = request.headers.get("stripe-signature")!

  let event: Stripe.Event

  try {
    event = stripe.webhooks.constructEvent(body, signature, webhookSecret)
  } catch (err: any) {
    console.error("[v0] Webhook signature verification failed:", err.message)
    throw new ValidationError("Invalid webhook signature")
  }

  console.log("[v0] Stripe webhook event:", event.type)

  // Handle checkout.session.completed
  if (event.type === "checkout.session.completed") {
    const session = event.data.object as Stripe.Checkout.Session

    console.log("[v0] Checkout session completed:", session.id)
    console.log("[v0] Customer email:", session.customer_email)
    console.log("[v0] Metadata:", session.metadata)

    const { churchName, planType, setupFeeTier } = session.metadata || {}

    if (!churchName || !session.customer_email) {
      throw new ValidationError("Missing required metadata: churchName or customer_email")
    }

    // Create church tenant with auto-generated code
    const supabase = await createClient()

    // Generate slug from church name
    const slug = churchName
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-")

    const { data: church, error: churchError } = await supabase
      .from("church_tenants")
      .insert({
        name: churchName,
        slug: slug,
        // church_code will be auto-generated by trigger
        stripe_customer_id: session.customer as string,
        stripe_subscription_id: session.subscription as string,
        subscription_plan: planType,
        subscription_status: "active",
      })
      .select()
      .single()

    if (churchError) {
      throw new DatabaseError("Failed to create church tenant", { originalError: churchError })
    }

    console.log("[v0] Church tenant created:", church.id)
    console.log("[v0] Auto-generated church code:", church.church_code)

    // Send welcome email with church code
    try {
      await fetch(`${process.env.NEXT_PUBLIC_SITE_URL}/api/email/welcome`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          email: session.customer_email,
          churchName: churchName,
          churchCode: church.church_code,
          churchId: church.id,
        }),
      })
    } catch (emailError) {
      console.error("[v0] Error sending welcome email:", emailError)
      // Don't fail the webhook if email fails
    }
  }

  return NextResponse.json({ received: true })
})
